export const categories: string[] = [
    "Amazon Renewed",
    "Amazon-Geräte & Zubehör",
    "Apps & Spiele",
    "Auto & Motorrad",
    "Baby",
    "Baumarkt",
    "Beleuchtung",
    "Bücher",
    "Bürobedarf & Schreibwaren",
    "Climate Pledge Friendly",
    "Computer & Zubehör",
    "Drogerie & Körperpflege",
    "DVD & Blu-ray",
    "Elektro-Großgeräte",
    "Elektronik & Foto",
    "Fashion",
    "Games",
    "Garten",
    "Geschenkgutscheine",
    "Gewerbe, Industrie & Wissenschaft",
    "Handmade-Produkte",
    "Haustier",
    "Kamera & Foto",
    "Kindle-Shop",
    "Kosmetik",
    "Küche, Haushalt & Wohnen",
    "Lebensmittel & Getränke",
    "Musik-CDs & Vinyl",
    "Musik-Downloads",
    "Musikinstrumente & DJ-Equipment",
    "Neue Fundstücke",
    "Prime Video",
    "Software",
    "Spielzeug",
    "Sport & Freizeit"
]